peartree/graph.py, peartree/summarizer.py, peartree/toolkit.py
Hi,
first of all thanks a lot of your library. I started to use partridge couple weeks ago and also found it really nice to use. Naturally i started to need graphs for some queries soon enough and did try out Peartree. First problem which i have ran into was that my source feed (Prague DPP) didn't have direction_id and that didn't play well with Peartree. Then i started to play around with path finding in the graph and it didn't seem to work correctly. After some playing around i have isolated the problem to the cross feed edge generation implementation - the transfer edges weren't generated. I've tried it on acdata and my gtfs feed and the behaviour which i have seen is that there were no cross feed edges actually added but rather a self loop edge is added for each node. I came up with …
=> Direction_id & Cross feed edges fixes

peartree/graph.py, peartree/toolkit.py
The two graph creation functions in graph.py have a lot of redundant operations. These are the funcs:
- populate_graph
- make_synthetic_system_network
This PR seeks to consolidate a number of those repeat operations into helper functions.
=> Refactor 2 graph creation steps

peartree/graph.py, peartree/paths.py, tests/test_paths.py
When we add a 2nd (3rd, 4th...) GTFS to an existing graph, we attempt to find connections between the two systems that are close and make them low/no-cost edge connectors.
This adds a parameter to make such it optional to exempt the new nodes from this step. Typically, you would do this with schedule data as the GTFS schedule should itself have the connections built in.
BUT when building stops and edges from a "synthetic" path, we want to make sure that we also create edges between the new paths created since they will not be naturally synced with each other (or each direction, for that matter).
=> Parameterize close-node edge creation on new nodes

requirements_dev.txt
Fixes https://github.com/kuanb/peartree/issues/37
Looks like there were some updates to the Jupyter client that caused that break to occur. Not sure exactly what, but just updated the dev dependencies to use the latest Jupyter libraries in the hopes that this will keep the notebook configuration up to date with the latest bug fixes (and, perhaps, also the latest bugs :) ).
=> [notebook] Update dev dependencies for make notebook

peartree/plot.py
Checks if display is available first, before attempting mpl's `.use('Agg')`
=> Avoid triggering matplotlib use Agg warnings

peartree/graph.py, peartree/summarizer.py, tests/test_paths.py
Two items in this PR:
- We take the absolute value of all edges as there are currently negative edges being calculated
- Note this is a fallback since these are "edge cases" in that they have to do with schedule data being staggered incorrectly, so we are just "wrapping around" the start/end of the schedule
- Adding a tag for walk segments when they are added to make it easy to identify walk transfers when they are generated
=> Negative edge cost fallback, tag mode

peartree/toolkit.py, tests/test_toolkit.py
Fixes https://github.com/kuanb/peartree/issues/42
API: ```Gc = pt.coalesce(G, 400)```
Where first arg is the Graph, and second is the threshold in the units currently relevant to the graph's set CRS.
=> Coalesce graph operation

peartree/graph.py, peartree/paths.py, peartree/summarizer.py, requirements.txt, tests/test_graph.py, tests/test_graph_assembly.py
This replaced work on https://github.com/kuanb/peartree/pull/51/files
From the previous PR:
Partially (incrementally) addressing issue #12
Parallelizes target route processing operation process_route_edges_and_wait_times via dask distributed which allows for modular parallelization architecture which in the future could leverage external resources (useful for large graphs, tethering together whole regions, etc.).
------
Updates unique to this new PR:
Using multiprocessing, _not_ Dask, for now. Change is incremental.
------
OLD:
Going with a Dask Bag for now. Keeping it simple for now, and can improve later.
Results from a quick test with AC Transit and the new system:
With `interpolate_times` set to `False`:
Without Dask (original method):
```
CPU times: user 40.4 s, sys: 920 ms, total: …
```
=> [performance] WIP Parallelization of route edge and wait costing iteration

.gitignore, Makefile, peartree/utilities.py, performance/run_etl.py
End visual:
Using snakeviz since it is "good enough" and much simpler than dealing with `kcachegrind` set up in an OS project...
=> [performance] cProfile and visualize library performance with a single script

peartree/summarizer.py
`apply_async` was for a single process. If we don't care about order, I believe `map_async` is the way to go. Perhaps best to preserve order of route ids for now, as we have other sort-based operations downstream (not that any were impacted by previous async method).
=> Use map operation on process pool

peartree/parallel.py, peartree/paths.py, peartree/summarizer.py, peartree/toolkit.py, performance/run_etl.py, tests/test_graph_assembly.py
Fixes https://github.com/kuanb/peartree/issues/59
Work towards dealing with https://github.com/kuanb/peartree/issues/12
Utilizes the `BaseManager` class to enable the `multiprocessing` `starmap` operation's mapped function to access a shared object containing read-only reference data needed by the function being run in parallel.
Short GIF capturing `htop` output while peartree is run on a sample GTFS feed in a docker container with access to 2 CPUs. 
Performance of `run_etl.py` profiler script (runs graph extraction on AC Transit feed) on 2016 MBP:
```
Parallelized, using 4 CPUs: 39s
Serial (no parallelization): 50s
```
H/T to @bryanculbertson for pointing me in the right direction with this.
=> [performance] Utilize mp.BaseManager to share reference object among processes

peartree/convert.py
Fixes https://github.com/kuanb/peartree/issues/19
We should still internally use MultiDiGraphs, but this allows for optimistic conversions (use fastest edge) to a "regular" DiGraph.
=> Convert option to digraph from multigraph

peartree/toolkit.py, tests/test_toolkit.py
Very much akin to the method of the same name in OSMnx (and have made sure to cite the function in the comments of the method). Has some updates that help with using the method with peartree, names:
- no list assembly of other misc. attributes
- checks to ensure that we don't simplify walk and transit mode segments
Note: Also relevant as a "good enough" replacement for the desired feature add in Issue https://github.com/kuanb/peartree/issues/46
=> Custom implementation of simplify_graph

peartree/toolkit.py, tests/test_toolkit.py
Fixes https://github.com/kuanb/peartree/issues/57
Conveniently leverages the new simplify operation added to resolve lost edges and hanging nodes issue.
Example of LA (which was not working before) working now:
=> Fix dropped edges during a coalesce operation

peartree/graph.py, peartree/paths.py, peartree/summarizer.py, tests/test_graph.py, tests/test_graph_assembly.py
Used to be hardcoded in the `generate_summary_wait_times` method, now make it a kwarg.
=> Thread through default fallback node/stop cost param

peartree/parallel.py, tests/test_paths.py
Fix issue https://github.com/kuanb/peartree/issues/89
=> [reliability] Consistent handling of direction_id when NaNs present

peartree/synthetic.py
Fixes https://github.com/kuanb/peartree/issues/84
=> [internal] Preserve units during reprojection

requirements.txt
Ensures users to do not use older versions of partridge, incl. versions susceptible to performance hits related to https://github.com/remix/partridge/issues/39
=> [performance] Use v0.11.0 of partridge or greater

.gitignore, .travis.yml, peartree/graph.py, peartree/paths.py, peartree/plot.py, peartree/synthetic.py, peartree/toolkit.py, requirements.txt, requirements_dev.txt, setup.py
Toolkit utilizes (part of) OSMnx's simplify graph step. This and the plot method are the only two steps that utilize OSMnx. Due to OSMnx's large array of capabilities, I'm opting to simply copy over the contents of the simplify graph method with minor modification (and full citation/reference to source material) into the peartree repo to attempt to reduce dependencies.
=> [simplify] Reduce dependencies in toolkit

peartree/graph.py, peartree/parallel.py, peartree/paths.py, peartree/summarizer.py, tests/test_graph.py, tests/test_graph_assembly.py, tests/test_paths.py
Fixes https://github.com/kuanb/peartree/issues/109
A user can now pass in a custom method for handling wait time. The default is set in paths under `_calculate_means_default`. A user could supply, say, a more optimistic operation to select the shortest delay between stops, or to note multimodal arrival distributions and account for them when determining edge cost.
=> [feature] Enable customized wait time estimation

peartree/graph.py, peartree/graph_tool.py, peartree/paths.py, peartree/summarizer.py
In addition to doc strings:
- move where SyntheticTransitNetwork validation occurs to path level operation
- break out average wait calculation from synthesized headways to a lambda operation (held in `unique_edge_operator`)
=> [documentation] Doc strings and light code gardening

peartree/parallel.py
For route processing - no need to perform second mask on target time subsetting every time a route is processed - just do it one time.
=> [performance] Trim by times only on init

peartree/toolkit.py, tests/test_toolkit.py
Using minimum of grouped edge weights effectively reduce path costs, and increase accessibility significantly.
The following map shows shortest path lengths from one single source to all destinations in Berkeley.
It changes from using original full network to coalesced network using min grouped edge weights. Noticing the shortest path lengths reduce significantly (darker color to lighter color)
The following map shows the same change but using coalesced network using mean (different color bins though). The change is less significant. 
Also some stats comparison:
**Stats** | **Full Network** | **Coalesced w Min** | **Coalesced w Mean**
--|--|--|--
Max shortest path length | 5172 | 3092 | 3493
Mean shortest path length | 2488 | 1383 | 1619
Visuals made by UrbanFootprint :))
=> [coalesce] Use mean of grouped edge weights rather than minimum

peartree/toolkit.py, tests/test_toolkit.py
1. Create defaults for boarding cost and edge cost summarizers, both separate from the other.
2. Update tests to ensure edge cost summarizer performing as intended.
=> [coalesce] Parameterize summary operations

peartree/paths.py, tests/test_graph.py
Fixes https://github.com/kuanb/peartree/issues/133
=> [wait_time_estimation] Trim zeroes in default wait time estimation

peartree/parallel.py, peartree/paths.py, tests/test_graph.py
Fixes https://github.com/kuanb/peartree/issues/131
=> [wait_time_estimation] Consider time frame start/end when evaluating boarding cost

setup.py
Lock to v1.0.0 on partridge dependency
Why? Since 1.1 has breaking changes
Do this until I update how Feed class is handled; then can update to 1.1
=> Lock to v1.0.0 on partridge

peartree/summarizer.py, tests/test_summarizer.py
When calculating node wait times, do not drop nodes that have just one wait time associated with them. For these, replace with the user-defaulted fallback wait time value.
Fixes https://github.com/kuanb/peartree/issues/139
TODO: Add tests specifically around there being only one stop time associated with that stop wait time estimate.
=> Do not prune trips with just one arrival time

peartree/toolkit.py
In addition to warning, comment points to https://github.com/kuanb/peartree/issues/126 for more details.
Helps prevent exploratory users from unintentionally undermining their graph through a naive coalesce op.
=> Add logger warning for coalesce function

peartree/graph.py, peartree/paths.py, peartree/summarizer.py, peartree/synthetic.py, peartree/toolkit.py, peartree/utilities.py, tests/test_graph_tool.py, tests/test_paths.py, tests/test_toolkit.py, tests/test_utilities.py
Include a list of all modes by GTFS mode id under each node produced for the NetworkX graph.
Fixes https://github.com/kuanb/peartree/issues/150
=> New attribute on stop nodes - modes list

peartree/toolkit.py
Fixes #136 
Update `pandas.Series.nonzero` (deprecated since 0.24.0 https://pandas.pydata.org/pandas-docs/version/0.25.3/reference/api/pandas.Series.nonzero.html) to `pandas.Series.to_numpy().nonzero`
=> Fix issue 136 - Use pandas.Series.to_numpy().nonzero

peartree/parallel.py
This is an completely untested proposed fix for https://github.com/kuanb/peartree/issues/165
=> Use the same DataFrame in the filter that is being filtered
