kuanb/peartree

peartree/graph.py, peartree/paths.py, peartree/toolkit.py
Closes https://github.com/kuanb/peartree/issues/1
=> Identify and generate x-feed transfer edges based proximity threshold

peartree/graph.py, peartree/paths.py
Closes https://github.com/kuanb/peartree/issues/5
Drops subsetting of feed stops df on every row iteration (which was repeated 2x).
=> Refactor populate_graph and generate_cross_feed_edges

peartree/graph.py, peartree/summarizer.py, peartree/toolkit.py, tests/test_paths.py
A follow up to @pitrz 's https://github.com/kuanb/peartree/pull/16 (thanks again!). This adds tests that actually check the creation of connector edges (that they are created), as well as cleans up pruning of self node in finding nearest node (per this discussion https://github.com/kuanb/peartree/pull/16#discussion_r159263616).
=> Nearest node function clean up

.pre-commit-config.yaml, peartree/graph.py, peartree/paths.py, peartree/summarizer.py, tests/test_graph.py, tests/test_graph_assembly.py
Passes flag through (default true) to allow someone to opt out of using the stop times interpolation if they want to.
=> Set flag for stop times interpolation

peartree/graph.py, tests/test_paths.py
Fixes https://github.com/kuanb/peartree/issues/28
=> Enable bidirectional route creation on synthetic routes

peartree/graph.py, tests/test_paths.py
* Reuses nodes created from first direction
* Generated both edge directions in the same loop/add edge step
* Updates tests
=> Refactor implementation of bidirectional synthetic network

peartree/toolkit.py, tests/test_toolkit.py
Fixes https://github.com/kuanb/peartree/issues/47
=> Handle when node is not preserved in coalesce

peartree/toolkit.py, tests/test_toolkit.py
Fixes https://github.com/kuanb/peartree/issues/49
=> During coalesce, only re-add one representative min length edge

peartree/convert.py, tests/test_convert.py, tests/test_toolkit.py
Increase coverage and (better) test the functions that were introduced in the last two commits.
=> Update simplify test, add test for export to DiGraph

peartree/toolkit.py, tests/test_toolkit.py
Fixes https://github.com/kuanb/peartree/issues/65
=> Drop duplicate edges during simplify operation

.gitignore, peartree/graph.py, peartree/paths.py, peartree/synthetic.py, tests/test_paths.py
Addresses custom stops desire from Issue https://github.com/kuanb/peartree/issues/24
=> Custom stop coordinates for synthetic routes

peartree/utilities.py, tests/test_utilities.py
Fixes https://github.com/kuanb/peartree/issues/81
=> [feature] Save/read peartree graphs from zip

peartree/parallel.py
Fixes https://github.com/kuanb/peartree/issues/87
=> [performance] Use unique stop in generate_wait_times

peartree/summarizer.py
Stop time interpolation works on the entire `stop_times` df, majority of which will be tossed later based on given requested time range.
Trimming down stop_times before passing it to the stop time interpolation step increases performance by a huge amount. 
Here are some evidence of the performance gain on the `pt.paths.generate_summary_graph_elements` step:
**gtfs id** | **current version** | **with trimming**
--|--|--
f-9q9-bart | 9.0s,  97 edges,  50 stops | 3.8s,  97 edges,  50 stops
f-9q9-actransit | 132.0s,  5670 edges,  5050 stops | 59.8s,  5670 edges,  5050 stops
f-9q8y-sfmta | 131.3s,  3806 edges,  3409 stops | 66.7s,  3806 edges,  3409 stops
f-9qb-goldengatetransit | 10.6s,  519 edges,  473 stops | 7.5s,  519 edges,  473 stops
f-9qc-fairfield~ca~us | 5.0s,  280 edges,  245 stops …
=> [performance] Trim stop_times before stop time interpolation

peartree/summarizer.py
Fixes https://github.com/kuanb/peartree/issues/82
=> Improve performance of gather op in RouteProcessor

peartree/graph.py, peartree/paths.py, peartree/synthetic.py, tests/test_utilities.py
Fixes https://github.com/kuanb/peartree/issues/102
(Also starting to sprinkle in some doc strings...)
=> TransitJSON class with validation on instantiation

.travis.yml
Fixes https://github.com/kuanb/peartree/issues/105
=> [testing] Speed up travis tests, fix codecov reporting

peartree/synthetic.py
Fixes https://github.com/kuanb/peartree/issues/74
=> Update TransitJSON class docstring

peartree/toolkit.py, tests/test_toolkit.py
Fixes https://github.com/kuanb/peartree/issues/114
cc @yiyange (thanks for the issue!)
=> [reproject] Reassign CRS after reprojection

peartree/graph_tool.py, peartree/parallel.py, peartree/paths.py, peartree/plot.py, peartree/summarizer.py, tests/test_convert.py, tests/test_graph.py, tests/test_graph_assembly.py, tests/test_graph_tool.py, tests/test_paths.py
Fixes https://github.com/kuanb/peartree/issues/137
=> Ensure always subset stop id during wait time calc

setup.py
=> Revert "Lock to v1.0.0 on partridge"

peartree/paths.py, peartree/synthetic.py
Fixes https://github.com/kuanb/peartree/issues/146
=> [synthetic] Allow custom wait time calc as a synthetic parameter

peartree/synthetic.py, peartree/toolkit.py
Some minor clean up on how mode attribute is handled for 2 cases:
- synthetic lines and stops creation
- coalesce logic
=> Clean up handling of mode in synthetic graph creation, coalesce

.gitignore, .travis.yml, Dockerfile, requirements.txt, setup.py
Fixes https://github.com/kuanb/peartree/issues/156
- Adds explicit pandas dependencies
- Also updates travis tests to import from xenial's libgdal (libgdal1i instead of 1h)
=> Support new pandas

peartree/parallel.py, tests/test_parallel.py
Fixes https://github.com/kuanb/peartree/issues/170
cc @bryanculbertson
=> Test wait time generation logic for handling direction id subsetting
